---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "Drop AT&T neutron ha tool"
  copy:
    src: "neutron-ha-tool.py"
    dest: "/opt/neutron-ha-tool.py"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Convert the hostname to an int
  name2int:
    name: "{{ inventory_hostname }}"
  register: hashed_name

- name: Create Neutron HA
  cron:
    name: "{{ item.name }}"
    minute: "*/1"
    day: "*"
    hour: "*"
    month: "*"
    state: present
    job: "sleep {{ hashed_name.int_value }} && . /root/openrc && /opt/neutron-ha-tool.py {{ item.command }}"
    user: root
    cron_file: "{{ item.name }}"
  with_items:
    - { name: "l3_agent_migrate", command: "--l3-agent-migrate" }
    - { name: "replicate_dhcp", command: "--replicate-dhcp" }
